### ISSUE TITLE
api/assets/v1/assets 添加资产没有成功

### ISSUE THREAD

**Issue by ZuoGuocai** [tools-ops/jms-assets-import#3]
我用的jumpserver Version 1.4.9-2 GPLv2.  通过POST api/assets/v1/assets 添加资产没有成功，直接返回了所有资产信息。你是如果处理的？

**Comment by Gourds** [comment]
可以把注册的命令和具体报错发一下么

**Comment by ZuoGuocai** [comment]
`#!/usr/bin/env python

import requests
import json
from pprint import pprint
import ssl 
ssl._create_default_https_context = ssl._create_unverified_context


token = "41e59732b27080d00c7301b22ff3e93f9518ba6d"
header_info = {  "Authorization": 'Token ' + token }

query_args = {
         "id": "",
         "org_name": "DEFAULT",
         "org_id": "",
         "ip": "1.1.1.1",
         "hostname": "testtesttest",
         "protocol": ['ssh/22'],
         "platform": "Linux",
         "is_active": True,
         "admin_user": "e004ee55-4fb1-42be-ba7c-d2fef17341b5",
         "nodes": [
               "5d538cba-7683-4dca-864b-db7a8074ec76"
          ]

}
url ='https://test.com/api/assets/v1/assets'
response = requests.post(url,headers=header_info,data=json.dumps(query_args),verify=False)
pprint(json.loads(response.text))`

**Comment by Gourds** [comment]
protocols

**Comment by Gourds** [comment]
```
可以参考`http://your_host/api/assets/v1/`
{
	'hostname': 'xxx',
	'id': 'xxx-xxx-xxx-xxx',
	'ip': '1.1.1.1',
	'is_actice': 'true',
	'comment': '[xxx]',
	'nodes': ['xxx-xxx-xxx-xxx', 'xxx-xxx-xxx-xxx'],
	'domain': 'xxx-xxx-xxx-xxx',
	'admin_user': 'xxx-xxx-xxx-xxx',
	'protocols': ['ssh/22']
}
```
